### PR TITLE
Fixed the wrong message code, I hope

### LINKED ISSUE #5: Message code returns different message
https://github.com/AntidoteDB/antidote_ts_client/blob/master/src/messageCodes.ts#L64

In that line, `apbStaticUpdateObjects` generates `antidotePb.ApbUpdateObjects` (same as if it received code `apbUpdateObjects`.

Is there a reason for this?

Thanks!

### PR DESCRIPTION
**Pull request by filipesmedeiros**
This (I hope) closes #5.

### CODE REVIEW

**Comment by peterzeller** [comment]
Can you add a test for this case?

**Comment by filipesmedeiros** [comment]
@peterzeller I can try, yeah, but the first test you already have is triggering this error for me.

https://github.com/AntidoteDB/antidote_ts_client/blob/master/src/antidote.ts#L518

This function send a `MessageCodes.apbStaticUpdateObjects` to the server. So the weird thing here is that the client never receives this code (so this bug was never tested).

Should I create a test for something that isn't part of the client's spec?

**Comment by filipesmedeiros** [comment]
I should add why I came up with this, for context: creating a "proxy" for AntidoteDB, in TS. So I just forked this and created a socket that listens to connections with exactly the same API as Antidote. So i reused all the code generated from protobuf and stuff that you already had!

**Comment by peterzeller** [comment]
Ah, so this is actually dead code in the client but you reused the code for building a server?

Then we don't need a unit test.

**Comment by filipesmedeiros** [comment]
@peterzeller That's exactly right!

**Pull request merged**
